name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: General
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          user: Nestdot
          base: header, activity, metadata
          config_timezone: America/Asuncion
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: starred

      - name: Activity
        uses: lowlighter/metrics@latest
        with:
          filename: activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_visibility: public
          
      - name: Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: isoCalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: People
        uses: lowlighter/metrics@latest
        with:
          filename: people.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_types: followers
