name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: Nestdot
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Asuncion
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_activity: yes
          plugin_activity_visibility: public
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_people: yes
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: activity
